import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import SettingsProvider from "@/components/settings/settings-context";
import SettingsButton from "@/components/settings/settings-button";
import SettingsDialog from "@/components/settings/settings-dialog";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SettingsProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NextIntlClientProvider>
              {/* Top-right settings button */}
              <div className="fixed top-4 right-4 z-50">
                <SettingsButton />
              </div>

              {/* The dialog component is mounted at the root so it can be opened from anywhere */}
              <SettingsDialog />

              {children}
            </NextIntlClientProvider>
          </ThemeProvider>
        </SettingsProvider>
      </body>
    </html>
  );
}
